version: '2'

services:
    tileserver:
        image: klokantech/tileserver-gl
        volumes:
            - ./data:/data
        ports:
            - "8080:80"
        command: /data/output.mbtiles
    tippecanoe:
        image: tippecanoe
        volumes:
            - ./data:/data
            - ./src:/src
    node:
        image: webratio/nodejs-http-server:0.9.0
        volumes:
            - ./html:/opt/www
        ports:
            - "8888:8080"